### ISSUE TITLE
Clarification on states HDF5 input

### ISSUE THREAD

**Issue by b-carter** [HendrikStrobelt/LSTMVis#52]
Hi All,

Came across this project and it looks really helpful. I'm looking to use it to explore LSTM in a current project.

I'm a bit confused about the ``states.h5`` input file. I imagine that the state vector from each timestep is the ``h_t`` output of the LSTM, for each ``t`` (as in the notation of [this](http://colah.github.io/posts/2015-08-Understanding-LSTMs/img/RNN-unrolled.png) LSTM description). Is this correct?

If so, the states are dependent on the input sequence. So I can put any sequence into the LSTM and then get these hidden states, but wouldn't this tool also need the states from all of my other input sequences for some of the analysis? Or does it only look at one input at a time? Is there an easy way to swap between or compare activations across input sequences?

Thanks for the clarification, and for contributing this tool!

**Comment by sebastianGehrmann** [comment]
Hey, LSTMVis can handle any arbitrary n-dimensional sequences. We typically used the cell or hidden states of the LSTM. In [this](http://colah.github.io/posts/2015-08-Understanding-LSTMs/img/LSTM3-chain.png) picture, the horizontal at the top represents the cell state and h_t is the hidden state. 

With regard to your second question - You need to save all of the hidden states for all timesteps in your inputs (the `c_t` or `h_t` for all your `t`) in `states.h5`, so that you can evaluate the change over time. By selecting different timesteps in the tool, you can easily evaluate different sequences (given that you concatenated all your inputs and put them into the `states.h5`. If you want to directly compare activations between different sequences, there is right now no documented way of doing so, but if you are more specific, we can maybe point you in the right direction.

**Comment by HendrikStrobelt** [comment]
@b-carter does that solve your issue? feel free to close the issue if so. Thank you.

**Comment by b-carter** [comment]
Yeah, that was helpful, thanks!
