### ISSUE TITLE
Uncaught ReferenceError: HeatMap is not defined

### ISSUE THREAD

**Issue by qqdaiyu55** [HendrikStrobelt/LSTMVis#59]
**Example**: http://lstm.seas.harvard.edu/client/lstmvis.html?project=00parens&source=states::states2&activation=0.455&cw=30&meta=..&pos=150&wordBrush=..16,19&wordBrushZero=..1,0&sc=..440,625
**Browser**: Google Chrome 67.0.3396.99 (Official Build) (64-bit) on Mac OS
The errors in the console are pasted below:
```
Uncaught ReferenceError: HeatMap is not defined
    at LSTMHeatmapHandler.init (LSTMHeatmapHandler.js:25)
    at LSTMMatchView._initView (LSTMMatchView.js:52)
    at new LSTMMatchView (LSTMMatchView.js:21)
    at new LSTMVis (LSTMVis.js:15)
    at LSTMVis.js:79
```

**Comment by alxhrzg** [comment]
This is probably due to AdBlock blocking the Javascript Ressoure from loading. If your are in Chrome check the Console in the Developer Tools Menu. My browser showed this Error: `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`, before throwing the ReferenceError. To circumvent this problem, try to open the page in an Incognito Window or temporarily disable all Extensions. See more here: [https://stackoverflow.com/questions/22318119/i-am-getting-failed-to-load-resource-neterr-blocked-by-client-with-google-chr](url)
